### ISSUE TITLE
yarn dev環境で、Buyボタンを押すと Error: VM Exception while processing transaction: revert Not included in aave currencyが発生する。

### ISSUE THREAD

**Issue by mogiken** [taijusanagi/chocomint#31]
yarn dev環境で、Buyボタンを押すと Error: VM Exception while processing transaction: revert Not included in aave currencyが発生します。local環境でもaaveが必要なのでしょうか？

```
 Error: VM Exception while processing transaction: revert Not included in aave currency
      at Chocopound.balanceOf (contracts/dependencies/@openzeppelin/token/ERC1155/ERC1155.sol:77)
      at Chocopound.publishAndMintPrint (contracts/Chocopound.sol:154)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at EthModule._estimateGasAction (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:396:9)
      at HardhatNetworkProvider._sendWithLogging (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:22)
      at HardhatNetworkProvider.request (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:98:18)
      at JsonRpcHandler._handleRequest (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:187:20)
      at JsonRpcHandler._handleSingleRequest (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:166:17)
      at Server.JsonRpcHandler.handleHttp (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:51:21)
```

**Comment by mogiken** [comment]
stagingでは動作確認でき、devではaave関連がうまく動く感じがしないので、staging+kovan環境で動作確認してみます。

**Comment by taijusanagi** [comment]
ありがとうございます！

今回ちょっと開発環境でトリッキーなことをしているのですが、aaveはこちらにより、メインネットをフォークした環境をローカルに構築して連携する、という方法をとっています。動作検証時に下記のネットワークに接続できていますでしょうか？

```
"run-localchain": "yarn hardhat node --fork https://mainnet.infura.io/v3/95f65ab099894076814e8526f52c9149",
```

もしかしたら https://github.com/taijusanagi/chocomint/issues/30 こちらでchainIdを変更したことが動作に影響しているかもしれません！

**Comment by taijusanagi** [comment]
自分の環境でも確認できました、ちょっとパッとみた感じわからないので原因を確認しますね

<img width="1114" alt="Screen Shot 2021-03-23 at 1 02 40" src="https://user-images.githubusercontent.com/38043569/112020226-8263a380-8b73-11eb-831d-cfcb702761f1.png">

**Comment by taijusanagi** [comment]
こちらで修正しました。
https://github.com/taijusanagi/chocomint/commit/45f9357ef78310c28393b2358055d0d7c80c2f9b

動作確認
<img width="899" alt="Screen Shot 2021-03-23 at 1 25 57" src="https://user-images.githubusercontent.com/38043569/112023576-bab8b100-8b76-11eb-8383-a8529a64708b.png">

原因としては、コントラクトデプロイ時にaaveから対応トークンをとってきてApproveしているのですが、そこの部分のスクリプトが、テストネットデプロイ後にフロントの表示 WETH-> ETHの調整のために修正した箇所の影響でWETHがapproveされていなかったことが原因でした。

https://github.com/taijusanagi/chocomint/commit/ca56646ec83506faa082a3c643bcc0522f06efd6#diff-807dce668a24ba22e291030584f759db2b23eea87d830338af1bbd775d4b5883L9

Issueの作成ありがとうございました！

**Comment by mogiken** [comment]
> こちらで修正しました。
> [45f9357](https://github.com/taijusanagi/chocomint/commit/45f9357ef78310c28393b2358055d0d7c80c2f9b)
> 
> 動作確認
> <img alt="Screen Shot 2021-03-23 at 1 25 57" width="899" src="https://user-images.githubusercontent.com/38043569/112023576-bab8b100-8b76-11eb-8383-a8529a64708b.png">
> 
> 原因としては、コントラクトデプロイ時にaaveから対応トークンをとってきてApproveしているのですが、そこの部分のスクリプトが、テストネットデプロイ後にフロントの表示 WETH-> ETHの調整のために修正した箇所の影響でWETHがapproveされていなかったことが原因でした。
> 
> [ca56646#diff-807dce668a24ba22e291030584f759db2b23eea87d830338af1bbd775d4b5883L9](https://github.com/taijusanagi/chocomint/commit/ca56646ec83506faa082a3c643bcc0522f06efd6#diff-807dce668a24ba22e291030584f759db2b23eea87d830338af1bbd775d4b5883L9)
> 
> Issueの作成ありがとうございました！

devでも動作しました。ありがとうございます。
