### ISSUE TITLE
「Buy」ボタンを押して購入するとき、１回目の購入は問題ないが、画面を更新せずに連続して２回目の「Ｂｕｙ」を実行するとエラーが発生する。

### ISSUE THREAD

**Issue by mogiken** [taijusanagi/chocomint#32]
yarn dev環境で、
「Buy」ボタンを押して購入するとき、１回目の購入は問題ないが、画面を更新せずに連続して２回目の「Ｂｕｙ」を実行するとエラーが発生する。Contractでのpriceチェックですかね？
```
Error: VM Exception while processing transaction: revert msg value must be more than print price
      at Chocopound.balanceOf (contracts/dependencies/@openzeppelin/token/ERC1155/ERC1155.sol:77)
      at Chocopound.publishAndMintPrint (contracts/Chocopound.sol:223)
      at Chocopound.publishAndMintPrint (contracts/Chocopound.sol:154)
      at HardhatNode._mineBlockWithPendingTxs (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1003:21)
      at HardhatNode.mineBlock (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:321:16)
      at EthModule._sendTransactionAndReturnHash (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1223:18)
      at HardhatNetworkProvider._sendWithLogging (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:22)
      at HardhatNetworkProvider.request (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:98:18)
      at JsonRpcHandler._handleRequest (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:187:20)
      at JsonRpcHandler._handleSingleRequest (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:166:17)
```

**Comment by taijusanagi** [comment]
そうですね、価格が自動的に上がる、というところを実装したことにより、画面更新せずに2回連続で購入した場合、また同じタイミングで他の人が購入した場合はエラーになります。同じ人が購入した場合のところは、slippageを設定できるので意図的にこの値段までなら購入してもいい、というところを設定して購入することも必要になります。

このbonded curveによる価格決定は実験的な試みのため、少し実装面で甘いところがあるかもしれせんが、一旦実装の優先度は落としていました。
