### ISSUE TITLE
「sell」ボタンを押すとエラーになる。

### ISSUE THREAD

**Issue by mogiken** [taijusanagi/chocomint#33]
yarn dev環境で「sell」ボタンを押すとエラーになります。

```
Error: Transaction reverted without a reason
      at <UnrecognizedContract>.<unknown> (0x030ba81f1c18d280636f32af80b9aad02cf0854e)
      at <UnrecognizedContract>.<unknown> (0x030ba81f1c18d280636f32af80b9aad02cf0854e)
      at <UnrecognizedContract>.<unknown> (0xdcd33426ba191383f1c9b431a342498fdac73488)
      at Chocopound._withdraw (contracts/Chocopound.sol:379)
      at Chocopound.burnPrint (contracts/Chocopound.sol:295)
      at Chocopound.burnPrint (contracts/Chocopound.sol:278)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at EthModule._estimateGasAction (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:396:9)
      at HardhatNetworkProvider._sendWithLogging (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:22)
      at HardhatNetworkProvider.request (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:98:18)
      at JsonRpcHandler._handleRequest (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:187:20)
      at JsonRpcHandler._handleSingleRequest (/root/choco/chocomint/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:166:17)
```

**Comment by taijusanagi** [comment]
自分の環境ではETHで出品→購入→売却の手順でやるとできました
<img width="906" alt="Screen Shot 2021-03-23 at 20 45 38" src="https://user-images.githubusercontent.com/38043569/112141555-c2309680-8c18-11eb-8725-ac4227277426.png">

再現手順等教えていただけますか？

**Comment by mogiken** [comment]
再現性を確認してたのですが、yarn dev環境で、Buyボタンでも落ちるようになってしまいました。nonce errorのようです。動画で撮影しました。何度か再起動しても復旧しない状況です。
チェーンが壊れたのであれば、初期化する方法があれば共有していただけると助かります。

[動画](https://photos.app.goo.gl/JyC6qFyazva1riBR6)

**Comment by taijusanagi** [comment]
そうでした、ganacheやhardhatなどでローカルチェーンで開発を行う場合、metamaskがlocalchainでnonceがリセットされるのを更新してくれない現象があるので、マニュアルでこの方法でnonceリセットを行う必要があります！
https://btcgeek.com/how-to-set-nonce-in-metamask/

この方法はchocomint固有というよりも、metamaskの仕様ですので、こちら試していただけますでしょうか？

**Comment by mogiken** [comment]
そういえば、nonceのリセットの必要ありましたね。。。
久しぶりのSolidityの開発だったので、失念してました。
問題なく動作しました。

Buyでの購入時にはaaveにethが送金され、withdrawRoyaltyでアーティストが引き出すところまで理解できました。
getPricesでの価格の計算ロジックも面白いですね。
単純なNFTのMintや売買だけではなく、チャレンジングな内容が詰まっていて刺激になってます。
